from spacy_russian_tokenizer.src.hyphen_patterns import FOREIGN_SURNAME_PATTERNS, PRONOUN_PATTERNS, PARTICLE_PATTERNS, \
    ADVERB_PATTERNS, COMPOUND_PREPOSITION_PATTERNS, PROPER_NAMES_WITH_DIGITS_PATTERNS, \
    COMPOUND_WORDS_WITH_DIGIT_PATTERNS, GEOGRAPHIC_NAMES_PATTERNS, ORG_NAMES_PATTERNS, CONJUNCT_WORDS_PATTERNS, \
    DIRECTION_PATTERNS, MISC_HYPHEN_FORM_PATTERNS, LOANWORDS_PATTERNS, SYNTAGRUS_RARE_CASES, COMPOUND_NOUNS, \
    COMPOUND_ADJECTIVE_PATTERNS, ADDRESS_PATTERNS
from spacy_russian_tokenizer.src.bigram_patterns import PERCENTAGE_PATTERNS, TIME_PATTERNS
from spacy_russian_tokenizer.src.sentence_terminal_patterns import NO_TERMINAL_PATTERNS

MERGE_PATTERNS = FOREIGN_SURNAME_PATTERNS + PRONOUN_PATTERNS + PARTICLE_PATTERNS + ADVERB_PATTERNS + \
                 COMPOUND_PREPOSITION_PATTERNS + COMPOUND_WORDS_WITH_DIGIT_PATTERNS + \
                 GEOGRAPHIC_NAMES_PATTERNS + ORG_NAMES_PATTERNS + CONJUNCT_WORDS_PATTERNS + DIRECTION_PATTERNS + \
                 MISC_HYPHEN_FORM_PATTERNS + LOANWORDS_PATTERNS + SYNTAGRUS_RARE_CASES + COMPOUND_NOUNS + \
                 COMPOUND_ADJECTIVE_PATTERNS + ADDRESS_PATTERNS #+ PERCENTAGE_PATTERNS + TIME_PATTERNS + PROPER_NAMES_WITH_DIGITS_PATTERNS
